#!perl
use Mojo::Base -strict;
use Mojo::Redis;
use Data::Dumper;

my $r = Mojo::Redis->new;

$r->execute(
  (map { [split /\s/] } @ARGV),
  sub {
    shift;
    local $Data::Dumper::Terse = 1;
    local $Data::Dumper::Sortkeys = 1;
    print "---\n";
    print Dumper(@_);
    print "---\n";
    Mojo::IOLoop->stop;
  },
);

Mojo::IOLoop->start;
