--- #YAML:1.0
name:               Mojo-Redis
version:            0.9906
abstract:           Asynchronous Redis client for L<Mojolicious>.
author:
    - Marcus Ramberg <mramberg@cpan.org>
license:            artistic_2
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Test::More:  0.88
requires:
    Encode:           0
    Mojolicious:      3.0
    Protocol::Redis:  1.0
resources:
    bugtracker:  https://github.com/marcusramberg/mojo-redis/issues
    license:     http://dev.perl.org/licenses/
    repository:  http://github.com/marcusramberg/mojo-redis
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
